name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: swczhat
        password: czh19960802
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy --all docker://k8s.gcr.io/kube-apiserver:v1.27.4 docker://registry.cn-hangzhou.aliyuncs.com/czh-image/kube-apiserver:v1.27.4
         skopeo copy --all docker://k8s.gcr.io/kube-controller-manager:v1.27.4 docker://registry.cn-hangzhou.aliyuncs.com/czh-image/kube-controller-manager:v1.27.4
         skopeo copy --all docker://k8s.gcr.io/kube-scheduler:v1.27.4 docker://registry.cn-hangzhou.aliyuncs.com/czh-image/kube-scheduler:v1.27.4
         skopeo copy --all docker://k8s.gcr.io/kube-proxy:v1.27.4 docker://registry.cn-hangzhou.aliyuncs.com/czh-image/kube-proxy:v1.27.4
         skopeo copy --all docker://k8s.gcr.io/pause:3.2 docker://registry.cn-hangzhou.aliyuncs.com/czh-image/pause:3.2
         skopeo copy --all docker://k8s.gcr.io/etcd:3.4.13-0 docker://registry.cn-hangzhou.aliyuncs.com/czh-image/etcd:3.4.13-0
         skopeo copy --all docker://k8s.gcr.io/coredns:1.7.0 docker://registry.cn-hangzhou.aliyuncs.com/czh-image/coredns:1.7.0
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
